# Generated by Django 3.1.7 on 2021-02-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'ToDo'},
        ),
        migrations.AlterModelTable(
            name='todo',
            table='ToDo',
        ),
    ]
