# Generated by Django 3.1.7 on 2021-02-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210219_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-added_date'], 'verbose_name': 'ToDo'},
        ),
    ]
